-- Migration 0004 — human-friendly, date-sequential order numbers:
-- TB-YYYYMMDD-NNN (e.g. TB-20260915-001), replacing the old opaque
-- TB-<base36 timestamp><random> format. Generated by a single atomic SQL
-- function rather than in application code, so two orders submitted at the
-- exact same millisecond can never collide on the same number — the
-- `insert ... on conflict ... do update ... returning` below takes a
-- row-level lock on that day's counter row for the duration of the
-- statement, which is what makes it safe under concurrent requests.
--
-- Order numbers are opaque strings everywhere they're used in the app
-- (display + lookup key only, never parsed) — see src/lib/orders.ts,
-- confirmed by grep before writing this migration — so changing the format
-- is safe and needs no other code changes beyond how it's generated.

create table if not exists daily_order_seq (
  day date primary key,
  seq int not null default 0
);

create or replace function next_order_number() returns text as $$
declare
  v_day date := (now() at time zone 'Europe/Kyiv')::date;
  v_seq int;
begin
  insert into daily_order_seq (day, seq) values (v_day, 1)
  on conflict (day) do update set seq = daily_order_seq.seq + 1
  returning seq into v_seq;

  return 'TB-' || to_char(v_day, 'YYYYMMDD') || '-' || lpad(v_seq::text, 3, '0');
end;
$$ language plpgsql;
